
# 1. The Name
name: CI/CD - Safety On Speed Expo App
# the name shows up in Github's Actions tab.

# 2. The Triggers - to run this pipeline. 
on:
  push:
    branches: [main] # when you push to main or develop, it will run the workflow.

  pull_request:
    branches: [main] # when someone opens a pull request targeting the main branch.
    # runs a CI check before the code is merged. 

# 3. the Jobs - initiating ubunut machine, 
#             - setting the enivironment + dependencies
#             - running the tests
#             - the CI part
jobs: 
  
  test:

    name: Lint and Test # name will be displayed in  Github UI
    runs-on: ubuntu-latest # this test will run on Github's free Ubuntu machine

    steps: # is the commands and actions of the job

      # Action step - runs a prebuilt tool
       - uses: actions/checkout@v4 # downloads the app source code (our repo) onto Ubuntu

       - name: Setup Node.js
         uses: actions/setup-node@v4 # installs Node.JS
         with:
           node-version: 20 # installs Node version 20
           cache: npm       # the npm modules will be held as cache

        
          # Command step  - executes terminal commands
       - name: Install dependencies
         run: npm ci #installs dependencie packages from package-lock.json.
       #better than  "npm install"

       # Command step 
       - name: Lint
         run: npm run lint # linter is the one that catches errors. 
         #our linter is ESLint. it is configured in the eslint.config.js file
      
      # Command step
       - name: Run tests
         run: npm test --passWithNoTests # runs the Jest tests
         # passWithNoTests is used to pass the tests even if there are no tests

# Job 2 : Deploy (build)
  build:
      name: EAS build # Expo Application Services
      runs-on: ubuntu-latest
      needs: test  #waits for tests to past first.

      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      # this runs only when the branch is 'main' AND the trigger is a 'push'

      steps:
        - uses: actions/checkout@v4
        # downloads the code onto the new machine.
        # each job is a FRESH machine so it gets repeated every time.

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: npm
